.PHONY: clean All

All:
	@echo "----------Building project:[ softwarePrototype - Debug ]----------"
	@cd "softwarePrototype" && "$(MAKE)" -f  "softwarePrototype.mk"
clean:
	@echo "----------Cleaning project:[ softwarePrototype - Debug ]----------"
	@cd "softwarePrototype" && "$(MAKE)" -f  "softwarePrototype.mk" clean
